const SUCCESS = ':SUCCESS';
const ERROR   = ':ERROR';

// reducer/ACTION_TYPE
export const THEME_CHANGE = 'themes/THEME_CHANGE';
export const CHANGE_LOCALE = 'i18n/CHANGE_LOCALE';

export const LOAD_SYMTOPMS_AND_SOLUTIONS = 'solutions/LOAD_SYMTOPMS_AND_SOLUTIONS';
export const LOAD_SYMTOPMS_AND_SOLUTIONS_SUCCESS = LOAD_SYMTOPMS_AND_SOLUTIONS + SUCCESS;
export const LOAD_SYMTOPMS_AND_SOLUTIONS_ERROR = LOAD_SYMTOPMS_AND_SOLUTIONS + ERROR;
export const CREATE_SYMTOPMS_AND_SOLUTIONS = 'solutions/CREATE_SYMTOPMS_AND_SOLUTIONS';
export const CREATE_SYMTOPMS_AND_SOLUTIONS_SUCCESS = CREATE_SYMTOPMS_AND_SOLUTIONS + SUCCESS;
export const CREATE_SYMTOPMS_AND_SOLUTIONS_ERROR = CREATE_SYMTOPMS_AND_SOLUTIONS + ERROR;
export const UPDATE_SYMTOPMS_AND_SOLUTIONS = 'solutions/UPDATE_SYMTOPMS_AND_SOLUTIONS';
export const UPDATE_SYMTOPMS_AND_SOLUTIONS_SUCCESS = UPDATE_SYMTOPMS_AND_SOLUTIONS + SUCCESS;
export const UPDATE_SYMTOPMS_AND_SOLUTIONS_ERROR = UPDATE_SYMTOPMS_AND_SOLUTIONS + ERROR;
export const FIND_SOLUTIONS = 'solutions/FIND_SOLUTIONS';
export const FIND_SOLUTIONS_SUCCESS = FIND_SOLUTIONS + SUCCESS;
export const FIND_SOLUTIONS_ERROR = FIND_SOLUTIONS + ERROR;
export const CLEAR_SOLUTIONS ='solutions/CLEAR_SOLUTIONS' ;
